name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Build (all envs in platformio.ini)
        run: pio run

      - name: Collect firmware artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          find .pio -type f \( -name "*.bin" -o -name "*.elf" -o -name "*.map" \) -exec cp {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pio-build-${{ github.sha }}
          path: artifacts
          retention-days: 7
